# Generated by Django 5.2.1 on 2025-06-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/iPhone15.avif', upload_to='products/'),
        ),
    ]
